# Generated by Django 5.2 on 2026-05-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cassa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
