# Generated by Django 5.2 on 2026-05-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cassa", "0002_alter_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("coffee", "Caffè"),
                    ("cup-soda", "Bibita"),
                    ("beer", "Birra"),
                    ("wine", "Vino"),
                    ("martini", "Cocktail"),
                    ("glass-water", "Acqua"),
                    ("milk", "Latte"),
                    ("sandwich", "Panino"),
                    ("pizza", "Pizza"),
                    ("salad", "Insalata"),
                    ("croissant", "Cornetto"),
                    ("cake-slice", "Dolce"),
                    ("cookie", "Biscotto"),
                    ("ice-cream-cone", "Gelato"),
                    ("popcorn", "Snack"),
                    ("egg-fried", "Uovo"),
                    ("beef", "Carne"),
                    ("fish", "Pesce"),
                    ("apple", "Frutta"),
                    ("carrot", "Verdura"),
                    ("utensils", "Piatto"),
                    ("soup", "Zuppa"),
                    ("candy", "Caramella"),
                    ("wheat", "Pane"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
