# Generated by Django 5.2 on 2026-06-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cassa", "0004_operator_cashwithdrawal"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="print_destinations",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Destinazioni extra: cucina,bar",
                max_length=50,
            ),
        ),
    ]
