# Generated by Django 5.2 on 2026-06-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cassa", "0005_product_print_destinations"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
