# Generated by Django 5.2 on 2026-06-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cassa", "0006_order_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("port", models.PositiveIntegerField(default=9100)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Stampante cassa (default)"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="print_destinations",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nomi stampanti extra separati da virgola",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="printers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Stampanti extra oltre a quella di default",
                related_name="products",
                to="cassa.printer",
            ),
        ),
    ]
