# Generated by Django 5.2 on 2026-06-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cassa", "0007_printer_alter_product_print_destinations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="printer",
            name="paper_width_chars",
            field=models.PositiveIntegerField(
                choices=[(32, "58mm (32 car.)"), (48, "80mm (48 car.)")],
                default=32,
                help_text="Caratteri per riga",
            ),
        ),
    ]
