# Generated by Django 5.2 on 2026-06-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cassa", "0008_printer_paper_width_chars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printer",
            name="paper_width_chars",
            field=models.PositiveIntegerField(
                choices=[
                    (32, "58mm (32 car.)"),
                    (42, "72mm (42 car.)"),
                    (48, "80mm (48 car.)"),
                ],
                default=48,
                help_text="Caratteri per riga",
            ),
        ),
    ]
