# Generated by Django 5.2 on 2026-06-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cassa", "0009_alter_printer_paper_width_chars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printer",
            name="paper_width_chars",
            field=models.PositiveIntegerField(
                default=48, help_text="Caratteri per riga (80mm = 48)"
            ),
        ),
    ]
